---- Reset the tables for clean testing
--DELETE FROM user_boards;
--DELETE FROM users;
--
--CREATE TABLE boards (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--    board_key VARCHAR(255),  -- Changed from 'key' to 'board_key'
--    title VARCHAR(255),
--    PRIMARY KEY (id)
--);


-- last one USED
-- Insert sample user data
--INSERT INTO users (id, first_name, last_name, username, password)
--VALUES
--    (1, 'John', 'Doe', 'john_doe', 'password123'),
--    (2, 'Jane', 'Smith', 'jane_smith', 'password456');

-- Optional: Link users to boards (example, assuming `user_boards` table structure)
-- INSERT INTO user_boards (user_id, board_id) VALUES (1, 1), (2, 2);

INSERT INTO users (id, first_name, last_name, username, password) VALUES
(1, 'John', 'Doe', 'testuser', 'password123'),
(2, 'Jane', 'Smith', 'jane_smith', 'password456');

